"""
Django settings for home project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n!=7ar3)qi@14_^ta4g=c!4nf_%ryny(sn931@wv+nkj!k0wpg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['web-production-f2d9a.up.railway.app', 'localhost', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
    'jazzmin',  # PHẢI ĐẶT TRƯỚC 'django.contrib.admin'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modeltranslation',
    'myapp',
    'cloudinary_storage',  # BẮT BUỘC
    'cloudinary',
    'mathfilters',  # THÊM DÒNG NÀY
    'ckeditor',           # THÊM DÒNG NÀY
    'ckeditor_uploader',  # THÊM DÒNG NÀY (để upload ảnh)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'home.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'home.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # ĐÚNG: trỏ vào E:\Web_wecamp\static
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # ĐÚNG

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'wecampofficial@gmail.com'  # Email của bạn
EMAIL_HOST_PASSWORD = 'qtzu yxtf evcz mjjm'  # App Password (xem bên dưới)
DEFAULT_FROM_EMAIL = 'Wecamp Cafe Retreat <wecampofficial@gmail.com>'

# thư viện
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



## Cloudinary Configuration
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name='dfqcrzpqr',  # Thay bằng cloud name của bạn
    api_key='864987181229665',     # Thay bằng API Key
    api_secret='oF29rJY-AksBR3AMURb-TGXVFAs',  # Thay bằng API Secret
)

# Media storage cho Cloudinary
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Cấu hình Cloudinary Storage
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dfqcrzpqr',
    'API_KEY': '864987181229665',
    'API_SECRET': 'oF29rJY-AksBR3AMURb-TGXVFAs',
}

# Thư mục upload ảnh
CKEDITOR_UPLOAD_PATH = "uploads/"

# Cấu hình CKEditor
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 400,
        'width': '100%',
    },
}


# settings.py
JAZZMIN_SETTINGS = {
    "site_title": "Wecamp Cafe Retreat",
    "site_header": "WECAMP ADMIN",
    "site_brand": "Wecamp",
    "site_logo": "admin/img/logo/logo.svg",  # Đặt logo vào static/admin/img/logo.svg
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": "admin/img/favicon.png",
    "welcome_sign": "Chào mừng đến Wecamp Admin",
    "copyright": "Wecamp Cafe Retreat",
    "search_model": ["main.Booking", "main.ContactMessage", "main.BookingInquiry"],

    # MÀU CHỦ ĐẠO WECAMP (XANH LÁ SANG)
    "topmenu_links": [
        {"name": "Trang chủ", "url": "/", "new_window": True},
        {"name": "Website", "url": "/", "new_window": True},
    ],

    "usermenu_links": [
        {"name": "Xem website", "url": "/", "new_window": True},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["main", "auth"],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.Booking": "fas fa-calendar-check",
        "main.ContactMessage": "fas fa-envelope",
        "main.BookingInquiry": "fas fa-headset",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": False,
    "custom_css": "admin/css/custom-admin.css",
    "custom_js": None,
    "show_ui_builder": True,

    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "default",  # hoặc "darkly", "lux", "cyborg"
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

from django.utils.translation import gettext_lazy as _

# home/settings.py
LANGUAGE_CODE = 'vi'  # Mặc định tiếng Việt

LANGUAGES = [
    ('vi', 'Tiếng Việt'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
TIME_ZONE = 'UTC'
# BẬT I18N
USE_I18N = True
USE_L10N = True
USE_TZ = True

# DÙNG pymysql làm driver cho MySQL
if 'DATABASE_URL' in os.environ:
    import pymysql
    pymysql.install_as_MySQLdb()  # QUAN TRỌNG!

    DATABASES = {
        'default': dj_database_url.parse(os.environ['DATABASE_URL'])
    }
else:
    # Local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }