# Generated by Django 4.2.25 on 2025-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bookinginquiry_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Ảnh')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('season', models.CharField(choices=[('spring', 'Xuân'), ('summer', 'Hạ'), ('autumn', 'Thu'), ('winter', 'Đông')], default='spring', max_length=20, verbose_name='Mùa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
            ],
            options={
                'verbose_name': 'Ảnh Thư Viện',
                'verbose_name_plural': 'Ảnh Thư Viện',
                'ordering': ['-created_at'],
            },
        ),
    ]
