# Generated by Django 4.2.25 on 2025-10-31 16:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_galleryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('featured', 'Nổi bật'), ('headline', 'Tiêu đề'), ('regular', 'Thường')], default='regular', max_length=20, verbose_name='Loại bài viết')),
                ('category', models.CharField(choices=[('weather', 'Thời tiết'), ('landscape', 'Cảnh quan'), ('news', 'Tin tức')], default='news', max_length=20, verbose_name='Chủ đề')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề chính')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Tiêu đề phụ')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Ảnh bài viết')),
                ('author_name', models.CharField(default='Admin', max_length=100, verbose_name='Tên người đăng')),
                ('author_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh người đăng')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đã xuất bản')),
            ],
            options={
                'verbose_name': 'Bài Viết',
                'verbose_name_plural': 'Bài Viết',
                'ordering': ['-published_at'],
            },
        ),
    ]
