# Generated by Django 4.2.25 on 2025-11-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking_combo_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Ngày'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='SĐT'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=5, verbose_name='Giờ'),
        ),
    ]
