# Generated by Django 4.2.25 on 2025-11-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_combo_meal_type_alter_menuitem_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wecamp/combos/', verbose_name='Hình ảnh'),
        ),
    ]
