# Generated by Django 4.2.25 on 2025-11-02 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_tent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Ảnh khách hàng')),
                ('service', models.CharField(choices=[('meal', 'Nhà Hàng'), ('coffee', 'Đồ Uống'), ('herbal_foot_soak', 'Ngâm chân thảo mộc'), ('tent_rental', 'Nghỉ Dưỡng'), ('art_activity', 'Vẽ tranh & tô tượng'), ('campfire', 'Lửa trại & nướng kẹo'), ('other', 'Khác')], max_length=50, verbose_name='Dịch vụ trải nghiệm')),
                ('content', models.TextField(verbose_name='Nội dung đánh giá')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Hiển thị trên trang chủ')),
            ],
            options={
                'verbose_name': 'Đánh giá khách hàng',
                'verbose_name_plural': 'Đánh giá khách hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
