# Generated by Django 4.2.25 on 2025-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đặt bàn / Dịch vụ', 'verbose_name_plural': 'Đặt bàn / Dịch vụ'},
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Đã xử lý')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('meal', 'Nhà Hàng'), ('coffee', 'Đồ Uống'), ('herbal_foot_soak', 'Ngâm chân thảo mộc'), ('tent_rental', 'Nghỉ Dưỡng'), ('art_activity', 'Vẽ tranh & tô tượng'), ('campfire', 'Lửa trại & nướng kẹo'), ('other', 'Khác')], default='meal', max_length=50, verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(help_text='VD: 13:30', max_length=5, verbose_name='Giờ'),
        ),
    ]
