# Generated by Django 4.2.25 on 2025-11-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_bookinginquiry_is_processed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AddField(
            model_name='booking',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=10, null=True, verbose_name='Số tiền Bill'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('meal', 'Nhà Hàng'), ('coffee', 'Đồ Uống'), ('herbal_foot_soak', 'Ngâm chân thảo mộc'), ('tent_rental', 'Nghỉ Dưỡng'), ('art_activity', 'Vẽ tranh & tô tượng'), ('campfire', 'Lửa trại & nướng kẹo'), ('other', 'Khác')], max_length=50, verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=5, verbose_name='Giờ'),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('month', models.CharField(choices=[('1', 'Tháng 1'), ('2', 'Tháng 2'), ('3', 'Tháng 3'), ('4', 'Tháng 4'), ('5', 'Tháng 5'), ('6', 'Tháng 6'), ('7', 'Tháng 7'), ('8', 'Tháng 8'), ('9', 'Tháng 9'), ('10', 'Tháng 10'), ('11', 'Tháng 11'), ('12', 'Tháng 12')], max_length=2, verbose_name='Tháng')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng doanh thu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doanh thu',
                'verbose_name_plural': 'Báo cáo doanh thu',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
