# Generated by Django 4.2.25 on 2025-11-02 16:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_booking_options_booking_bill_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đặt bàn / Dịch vụ', 'verbose_name_plural': 'Đặt bàn / Dịch vụ'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bill_amount',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('meal', 'Nhà Hàng'), ('coffee', 'Đồ Uống'), ('herbal_foot_soak', 'Ngâm chân thảo mộc'), ('tent_rental', 'Nghỉ Dưỡng'), ('art_activity', 'Vẽ tranh & tô tượng'), ('campfire', 'Lửa trại & nướng kẹo'), ('other', 'Khác')], default='meal', max_length=50, verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(help_text='VD: 13:30', max_length=5, verbose_name='Giờ'),
        ),
    ]
