# Generated by Django 4.2.25 on 2025-11-03 07:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_delete_revenue_delete_tour_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Nội dung'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_vi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Nội dung'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tiêu đề phụ'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_vi',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tiêu đề phụ'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Tiêu đề chính'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_vi',
            field=models.CharField(max_length=200, null=True, verbose_name='Tiêu đề chính'),
        ),
        migrations.AddField(
            model_name='combo',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Mô tả ngắn'),
        ),
        migrations.AddField(
            model_name='combo',
            name='description_vi',
            field=models.TextField(null=True, verbose_name='Mô tả ngắn'),
        ),
        migrations.AddField(
            model_name='combo',
            name='details_en',
            field=models.TextField(blank=True, null=True, verbose_name='Chi tiết món'),
        ),
        migrations.AddField(
            model_name='combo',
            name='details_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Chi tiết món'),
        ),
        migrations.AddField(
            model_name='combo',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên combo'),
        ),
        migrations.AddField(
            model_name='combo',
            name='title_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên combo'),
        ),
        migrations.AddField(
            model_name='drink',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='drink',
            name='description_vi',
            field=models.TextField(null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='drink',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên đồ uống'),
        ),
        migrations.AddField(
            model_name='drink',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên đồ uống'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_vi',
            field=models.TextField(null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên món'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên món'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Nội dung đánh giá'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_vi',
            field=models.TextField(null=True, verbose_name='Nội dung đánh giá'),
        ),
        migrations.AddField(
            model_name='tent',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='tent',
            name='description_vi',
            field=models.TextField(null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='tent',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên lều'),
        ),
        migrations.AddField(
            model_name='tent',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên lều'),
        ),
    ]
