# Generated by Django 4.2.25 on 2025-10-31 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ & Tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('date', models.DateField(verbose_name='Ngày đặt')),
                ('people', models.PositiveIntegerField(verbose_name='Số lượng người')),
                ('service', models.CharField(choices=[('meal', 'Dùng bữa'), ('coffee', 'Uống cafe'), ('herbal_foot_soak', 'Ngâm chân thảo mộc'), ('tent_rental', 'Thuê lều'), ('art_activity', 'Vẽ tranh & tô tượng'), ('other', 'Khác')], max_length=50, verbose_name='Dịch vụ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian gửi')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Đã xử lý')),
            ],
            options={
                'verbose_name': 'Yêu cầu tư vấn',
                'verbose_name_plural': 'Yêu cầu tư vấn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
