# Generated by Django 4.2.25 on 2025-10-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Dùng &lt;h2&gt;, &lt;h3&gt; để tạo mục lục tự động', verbose_name='Nội dung'),
        ),
    ]
