# Generated by Django 4.2.25 on 2025-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('date', models.DateField(verbose_name='Ngày đặt')),
                ('time', models.CharField(help_text='VD: 13:30, 19:15', max_length=5, verbose_name='Giờ đặt')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('service', models.CharField(default='meal', max_length=50, verbose_name='Dịch vụ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đặt')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Đã xác nhận')),
            ],
            options={
                'verbose_name': 'Đặt Bàn',
                'verbose_name_plural': 'Đặt Bàn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên combo')),
                ('description', models.TextField(verbose_name='Mô tả ngắn')),
                ('details', models.TextField(blank=True, verbose_name='Chi tiết món')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá gốc')),
                ('discount_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá ưu đãi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='combos/', verbose_name='Hình ảnh')),
                ('meal_type', models.CharField(choices=[('nuong', 'Set Nướng'), ('lau', 'Set Lẩu'), ('mon_le', 'Món Lẻ')], default='mon_le', max_length=20, verbose_name='Loại combo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Danh Sách Combo',
                'ordering': ['meal_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên món')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Hình ảnh')),
                ('meal_type', models.CharField(choices=[('nuong', 'Set Nướng'), ('lau', 'Set Lẩu'), ('mon_le', 'Món Lẻ')], default='mon_le', max_length=20, verbose_name='Loại món')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn phục vụ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
            ],
            options={
                'verbose_name': 'Món Ăn',
                'verbose_name_plural': 'Menu',
                'ordering': ['meal_type', 'name'],
            },
        ),
    ]
