# Generated by Django 4.2.25 on 2025-11-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_booking_options_remove_booking_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='meal_type',
            field=models.CharField(choices=[('nuong', 'Set Nướng'), ('lau', 'Set Lẩu'), ('mon_le', 'Món Lẻ'), ('combo', 'Combo')], default='mon_le', max_length=20, verbose_name='Loại combo'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('nuong', 'Set Nướng'), ('lau', 'Set Lẩu'), ('mon_le', 'Món Lẻ'), ('combo', 'Combo')], default='mon_le', max_length=20, verbose_name='Loại món'),
        ),
    ]
