# Generated by Django 4.2.25 on 2025-11-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_combo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đồ uống')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá')),
                ('image', models.ImageField(blank=True, null=True, upload_to='drinks/', verbose_name='Hình ảnh')),
                ('drink_type', models.CharField(choices=[('tra_sua', 'Trà Sữa'), ('ca_phe', 'Cà Phê'), ('nuoc_ep', 'Nước Ép'), ('tra_hoa_qua', 'Trà Hoa Quả'), ('nuoc_giai_khat', 'Nước Giải Khát')], default='coffee', max_length=20, verbose_name='Loại')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn phục vụ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
            ],
            options={
                'verbose_name': 'Đồ Uống',
                'verbose_name_plural': 'Menu Đồ Uống',
                'ordering': ['drink_type', 'name'],
            },
        ),
    ]
