# Generated by Django 4.2.25 on 2025-11-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên lều')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tents/', verbose_name='Hình ảnh')),
                ('tent_type', models.CharField(choices=[('overnight', 'Nghỉ Đêm'), ('day_use', 'Trong Ngày')], default='day_use', max_length=20, verbose_name='Loại lều')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Sức chứa')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn trống')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
            ],
            options={
                'verbose_name': 'Lều',
                'verbose_name_plural': 'Nghỉ Dưỡng',
                'ordering': ['tent_type', 'name'],
            },
        ),
    ]
