# Generated by Django 4.2.25 on 2025-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_booking_options_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginquiry',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Đã xử lý')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Đã xử lý')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='service',
            field=models.CharField(choices=[('meal', 'Nhà Hàng'), ('coffee', 'Đồ Uống'), ('herbal_foot_soak', 'Ngâm chân thảo mộc'), ('tent_rental', 'Nghỉ Dưỡng'), ('art_activity', 'Vẽ tranh & tô tượng'), ('campfire', 'Lửa trại & nướng kẹo'), ('other', 'Khác')], max_length=50, verbose_name='Dịch vụ'),
        ),
    ]
